apiVersion: v1
kind: Secret
metadata:
  name: deliverybot-token
  namespace: cicd
  annotations:
    kubernetes.io/service-account.name: deliverybot-sa
    kubernetes.io/service-account.namespace: cicd
type: kubernetes.io/service-account-token
